import "./globals.css";
import { Poppins } from "next/font/google";
import Providers from "./providers";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // los pesos que quieras usar
  display: "swap",
});

export const metadata = {
  title: "EventMatch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
